version: "3.9"
services:
  app:
    image: go-gin-movies
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./app"]
    environment:
      DB_TYPE: postgres
      DB_CONNECTION_STRING: "host=db user=postgres password=example dbname=postgres port=5432 sslmode=disable"
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    restart: always
